SimpleNotesApp/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace SimpleNotesApp.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

SimpleNotesApp/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using SimpleNotesApp.Data;
using SimpleNotesApp.Models;
using SimpleNotesApp.Services;

namespace SimpleNotesApp.Pages
{
    public class IndexModel : PageModel
    {
        private INoteData _noteData;
        //private SimpleNotesAppDbContext _context;

        public IndexModel(INoteData noteData)//, SimpleNotesAppDbContext context)
        {
            _noteData = noteData;
            //_context = context;
        }

        public IEnumerable<Note> Notes { get; set; }

        public IActionResult OnGet()
        {
            Notes = _noteData.GetAll();
            return Page();
        }

        [BindProperty]
        public Note Note { get; set; }


        // To żądanie uzupełnia formularz w modalu Edit (ajax)
        public IActionResult OnGetEditModalFormPartial(int id)
        {
            //Note = _context.Notes.Find(id);
            Note = _noteData.Get(id);
            return new PartialViewResult() { ViewName = "_EditModalFormPartial", ViewData = this.ViewData };
        }


        // Add note
        public async Task<IActionResult> OnPostAddAsync()
        {
            if (!ModelState.IsValid)
            {
                return RedirectToAction("Index");
            }

            if (Note.Title == null &&
                Note.Text == null &&
                Note.LinkToPic == null &&
                Note.Tags == null)
            {
                return RedirectToPage("Index");
            }

            //Set note create date
            Note.CreatedDate = DateTime.Now;

            if (Note.Tags != null)
            {
                //Removes spaces from string
                Note.Tags = Note.Tags.Replace(" ", String.Empty);
                //Removes all commas from the beginning and end of a string
                Note.Tags = Note.Tags.TrimStart(',').TrimEnd(',');
                //Removes all duplicate commas
                Note.Tags = Regex.Replace(Note.Tags, ",{2,}", ",");
            }

            _noteData.Add(Note);

            return RedirectToPage("Index");
        }

        // Update note
        public async Task<IActionResult> OnPostUpdateAsync()
        {
            if (!ModelState.IsValid)
            {
                return RedirectToAction("Error");  // ("Notes");
            }

            if (Note.Title == null &&
                Note.Text == null &&
                Note.LinkToPic == null &&
                Note.Tags == null)
            {
                return RedirectToPage("Index");
            }

            Note.ModifiedDate = DateTime.Now;

            if (Note.Tags != null)
            {
                //Removes spaces from string
                Note.Tags = Note.Tags.Replace(" ", String.Empty);
                //Removes all commas from the beginning and end of a string
                Note.Tags = Note.Tags.TrimStart(',').TrimEnd(',');
                //Removes all duplicate commas
                Note.Tags = Regex.Replace(Note.Tags, ",{2,}", ",");
            }

            _noteData.Update(Note);
            
            return RedirectToPage("Index");
        }
     

        // Delete note
        [BindProperty]
        public int? NoteId { get; set; }

        public async Task<IActionResult> OnPostDeleteAsync()
        {
            if (NoteId == null)
            {
                return NotFound();
            }

            _noteData.Delete(NoteId.GetValueOrDefault());

            return RedirectToPage("Index");
        }
    }
}

SimpleNotesApp/Pages/Index.cshtml
@page "{handler?}"
@using System.Linq
@model IndexModel

@{
    ViewData["Title"] = "Home page";
}

<!-- Add Button trigger modal -->
<div class="row m-3">
    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#addModal">
        + Add note
    </button>
</div>

<!-- Add Modal -->
<div class="modal fade" id="addModal">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">Add note</h5>
                <button type="button" class="close" data-dismiss="modal">
                    <span>&times;</span>
                </button>
            </div>
            <form method="post">
                <div class="modal-body">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="Note.Title" class="control-label"></label>
                        <input asp-for="Note.Title" class="form-control" />
                        <span asp-validation-for="Note.Title" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Note.Text" class="control-label"></label>
                        <textarea asp-for="Note.Text" class="form-control" rows="5"></textarea>
                        <span asp-validation-for="Note.Text" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Note.LinkToPic" class="control-label"></label>
                        <input asp-for="Note.LinkToPic" class="form-control" placeholder="e.g. www.myphotos.com/2SoFg4X.jpg" />
                        <span asp-validation-for="Note.LinkToPic" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Note.Tags" class="control-label"></label>
                        <input asp-for="Note.Tags" class="form-control" placeholder="funny, black, cat" />
                        <span asp-validation-for="Note.Tags" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Note.BackgroundColor" class="control-label"></label>
                        <br />

                        <div class="text-center">

                            @{
                                var baseColors = Enum.GetValues(typeof(Models.BaseColors)).Cast<Models.BaseColors>();


                                foreach (var color in baseColors)
                                {
                                    // Pierwszy element radio zostaje domyślnie zaznaczony
                                    if (baseColors.First() == color)
                                    {
                                        <label class="btn btn-@color">
                                            @Html.RadioButton("Note.BackgroundColor", color, true)
                                        </label>
                                    }
                                    else
                                    {
                                        <label class="btn btn-@color">
                                            @Html.RadioButton("Note.BackgroundColor", color)
                                        </label>
                                    }
                                }
                            }
                        </div>

                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary" asp-page-handler="Add">Create</button>
                    @*<input type="submit" class="btn btn-primary" asp-page-handler="Add" value="Create" />*@
                </div>
            </form>
        </div>
    </div>
</div>


<!-- Edit Modal Container-->
<div class="modal fade" id="editModal">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">Edit note</h5>
                <button type="button" class="close" data-dismiss="modal">
                    <span>&times;</span>
                </button>
            </div>
            <div id="editModalForm">
                <!-- partial _EditModalFormPartial -->
            </div>
        </div>
    </div>
</div>



<!-- Delete Modal -->
<div class="modal fade" id="deleteModal">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">Are you sure you want to delete this note?</h5>
                <button type="button" class="close" data-dismiss="modal">
                    <span>&times;</span>
                </button>
            </div>
            <div class="modal-body">
                This operation cannot be undone.
            </div>
            <div class="modal-footer">
                <form method="post">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <input type="hidden" asp-for="NoteId" id="inputNoteId" value="" />
                    <button type="submit" class="btn btn-danger" asp-page-handler="Delete">Delete</button>
                </form>
            </div>
        </div>
    </div>
</div>



<!-- Generuje wszystkie karty notatek na stronie -->
<div class="card-columns">
    @foreach (var note in Model.Notes.Reverse())
    {

        @await Html.PartialAsync("_NoteCard", note)

    }
</div>


<script>
            function setIdForDeleteModal(noteId) {
                document.getElementById("inputNoteId").value = noteId;
            }

            function getDataForEditModal(noteId) {
                $('#editModalForm').load('/EditModalFormPartial?id=' + noteId);
            }
</script>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SimpleNotesApp/Pages/_EditModalFormPartial.cshtml
@model IndexModel

@*@Model.Note.Id
    @Model.Note.Title
    @Model.Note.Text
    @Model.Note.Tags
    @Model.Note.CreateData
    @Model.Note.BackgroundColor
    @Model.Note.LinkToPic*@


@*nie trzeba dodawac value="...". To samo się dodaje.*@



<form method="post">
    <div class="modal-body">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <input type="hidden" asp-for="Note.Id" />
        <div class="form-group">
            <label asp-for="Note.Title" class="control-label"></label>
            <input asp-for="Note.Title" class="form-control" />
            <span asp-validation-for="Note.Title" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Note.Text" class="control-label"></label>
            <textarea asp-for="Note.Text" class="form-control" rows="5"></textarea>
            <span asp-validation-for="Note.Text" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Note.LinkToPic" class="control-label"></label>
            <input asp-for="Note.LinkToPic" class="form-control" placeholder="e.g. www.myphotos.com/2SoFg4X.jpg" />
            <span asp-validation-for="Note.LinkToPic" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Note.Tags" class="control-label"></label>
            <input asp-for="Note.Tags" class="form-control" placeholder="separate, tags, by, commas" />
            <span asp-validation-for="Note.Tags" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label asp-for="Note.BackgroundColor" class="control-label"></label>
            <br />

            <div class="text-center">
                @{
                    var baseColors = Enum.GetValues(typeof(Models.BaseColors)).Cast<Models.BaseColors>();

                    foreach (var color in baseColors)
                    {
                        <label class="btn btn-@color">
                            @Html.RadioButton("Note.BackgroundColor", color)
                        </label>
                    }
                }
            </div>
        </div>
    </div>

    <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-warning" asp-page-handler="Update">Apply changes</button>
    </div>
</form>

SimpleNotesApp/Pages/_NoteCard.cshtml
@model SimpleNotesApp.Models.Note

@{
    var bg_color = $"bg-{Model.BackgroundColor}";
    var text_color = (((int)Model.BackgroundColor == 1) ||
                      ((int)Model.BackgroundColor == 2) ||
                      ((int)Model.BackgroundColor == 4) ||
                      ((int)Model.BackgroundColor == 6) ||
                      ((int)Model.BackgroundColor == 8)) ? "text-white" : "";
    var card_img_style = ((Model.Title != null) ||
                           (Model.Text != null) ||
                           (Model.Tags != null)) ? "card-img-top" : "card-img";

}


<div class="card @bg_color @text_color show-more">


    @if (Model.LinkToPic != null)
    {
        <img class="@card_img_style" src="@Model.LinkToPic" alt="Card image cap">
    }

    @if ((Model.Title != null) || (Model.Text != null) || (Model.Tags != null))
    {
        <div class="card-body">

            @if (Model.Title != null)
            {
                <h5 class="card-title">@Model.Title</h5>
            }

            @if (Model.Text != null)
            {
                <p class="card-text">@Model.Text</p>
            }

            @if (Model.Tags != null)
            {
                var tags = Model.Tags.Split(',');
                foreach (var tag in tags)
                {
                    <a href="/Notes"><span class="badge badge-primary">#@tag</span></a>
                }
            }
        </div>
    }

    @*<div class="card-footer">
        <small class="text-muted">@Model.ModifiedDate</small>
    </div>*@


    <button type="submit" class="close edit-btn" onclick="getDataForEditModal(@Model.Id)" data-toggle="modal" data-target="#editModal">
        <span>
            &#x270f;
        </span>
    </button>
    <button type="button" class="close close-btn" onclick="setIdForDeleteModal(@Model.Id)" data-toggle="modal" data-target="#deleteModal">
        <span>
            &#x1f5d1;
        </span>
    </button>
</div>